### ISSUE TITLE
Can't set TGTG_TELEGRAM_TOKEN environment variable

### ISSUE THREAD

**Issue by mmmago** [HamletDuFromage/py-tgtg#1]
Hello,

I don't understand how to set the telegram token to environnement variable ? I have my token as "6185234662:AAE-XXXXX...", how to add it ?

thanks ,

**Comment by mmmago** [comment]
found it. 

os.environ['TGTG_TELEGRAM_TOKEN'] = '6185234662:AAE-XXXX...'

**Comment by HamletDuFromage** [comment]
https://doc.ubuntu-fr.org/variables_d_environnement
If I were you, I'd simply add it to .bashrc as to not have your private token floating around in your code

**Comment by HamletDuFromage** [comment]
Case in point, you uploaded your private token to GitHub: https://github.com/mmmago/node-toogoodtogo-watcher/commit/b2d8ee108dd0091c41a52156f29034c78bf0100f
You should refresh it asap
